.css-checkbox {
         display:none;
	}
.css-checkbox + .css-label {
padding-left:45px;
height:40px; 
display:inline-block;
line-height:40px;
background-repeat:no-repeat;
background-position: 0 0;
font-size:40px;
vertical-align:middle;
cursor:pointer;
}

.css-checkbox:checked + .css-label {
background-position: 0 -40px;
}
.css-label {
background-image:url(http://csscheckbox.com/checkboxes/u/csscheckbox_42e088649c54a88bb0d54d511861bc9f.png);
-webkit-touch-callout: none;
-webkit-user-select: none;
-khtml-user-select: none;
-moz-user-select: none;
-ms-user-select: none;
user-select: none;
}
